-- ============================================================================
-- Directors Dealings — Postgres schema (consolidated head)
-- B-175 / Cloud Migration M1. Target: Supabase Postgres 17.
--
-- This is the SQLite schema (db_schema.sql + migrations 002–016) collapsed into
-- a single idempotent Postgres DDL representing the FINAL table state. The
-- pipeline's per-connection migration replay is a SQLite artdefact; on Postgres
-- we start from this consolidated head and add new migrations going forward.
--
-- Translation decisions (parity-preserving):
--   * Dates stay TEXT (ISO-8601 strings) — the codebase compares them as
--     strings; ISO text sorts correctly in Postgres too. No DATE/TIMESTAMP cast.
--   * 0/1 flag columns stay INTEGER (the Python treats them as ints, not bools).
--   * Share/volume counts → BIGINT (can exceed 2^31 for large issuers).
--   * SQLite REAL (8-byte float) → DOUBLE PRECISION (not Postgres REAL/float4,
--     which would lose precision).
--   * AUTOINCREMENT id → BIGINT GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT so
--     the data migrator can insert the existing id values explicitly).
--   * Every natural upsert key is preserved as a PRIMARY KEY or UNIQUE so
--     `INSERT ... ON CONFLICT` has a constraint to target.
-- ============================================================================

-- ---------------------------------------------------------------- transactions
CREATE TABLE IF NOT EXISTS transactions (
    fingerprint     TEXT    PRIMARY KEY,
    first_seen      TEXT    NOT NULL,
    last_seen       TEXT    NOT NULL,
    seen_count      INTEGER NOT NULL DEFAULT 1,
    date            TEXT    NOT NULL,
    ticker          TEXT    NOT NULL,
    company         TEXT    NOT NULL,
    director        TEXT    NOT NULL,
    role            TEXT,
    type            TEXT    NOT NULL CHECK (type IN ('BUY','SELL','SELL_TAX','EXERCISE','GRANT','SIP')),
    shares          BIGINT  NOT NULL,
    price           DOUBLE PRECISION NOT NULL DEFAULT 0,
    value           DOUBLE PRECISION NOT NULL DEFAULT 0,
    context         TEXT,
    url             TEXT,
    announced_at    TEXT,
    cluster_id      TEXT,
    first_time_buy  INTEGER NOT NULL DEFAULT 0,
    -- migration 002 / 004 / 005 / 010 / 013
    parser_source   TEXT    NOT NULL DEFAULT 'regex',
    role_normalized TEXT,
    buy_strictness  VARCHAR(16),
    price_audit     TEXT,
    resulting_shares BIGINT
);
CREATE INDEX IF NOT EXISTS idx_tx_ticker_date ON transactions (ticker, date);
CREATE INDEX IF NOT EXISTS idx_tx_director    ON transactions (director);
CREATE INDEX IF NOT EXISTS idx_tx_type_date   ON transactions (type, date);
-- new (ADR §2b): the alpha-research scan axis
CREATE INDEX IF NOT EXISTS idx_tx_role_type_date ON transactions (role_normalized, type, date);

-- ---------------------------------------------------------------------- prices
CREATE TABLE IF NOT EXISTS prices (
    ticker      TEXT    NOT NULL,    -- '^FTAS' / '^FTNMX5710' for benchmark series
    date        TEXT    NOT NULL,
    open        DOUBLE PRECISION,
    high        DOUBLE PRECISION,
    low         DOUBLE PRECISION,
    close       DOUBLE PRECISION NOT NULL,
    volume      BIGINT,
    source      TEXT    NOT NULL DEFAULT 'yahoo',
    fetched_at  TEXT    NOT NULL,
    PRIMARY KEY (ticker, date)
);
CREATE INDEX IF NOT EXISTS idx_prices_date ON prices (date);

-- --------------------------------------------------------------- tickers_meta
CREATE TABLE IF NOT EXISTS tickers_meta (
    ticker             TEXT    PRIMARY KEY,
    sector             TEXT,
    benchmark_symbol   TEXT,
    is_aim             INTEGER NOT NULL DEFAULT 0,
    market_cap_gbp     DOUBLE PRECISION,
    updated_at         TEXT    NOT NULL,
    -- migration 003 / 006 / 007 / 011
    is_excluded_issuer INTEGER NOT NULL DEFAULT 0,
    excluded_source    TEXT,
    classified_at      TEXT,
    shares_outstanding DOUBLE PRECISION,
    website_url        TEXT,
    small_cap          INTEGER DEFAULT 0
);

-- --------------------------------------------------------------------- signals
CREATE TABLE IF NOT EXISTS signals (
    signal_id      TEXT NOT NULL,
    signal_version TEXT NOT NULL,
    fingerprint    TEXT NOT NULL,
    fired_at       TEXT NOT NULL,
    confidence     TEXT,
    metadata       TEXT,
    PRIMARY KEY (signal_id, signal_version, fingerprint),
    FOREIGN KEY (fingerprint) REFERENCES transactions (fingerprint)
);
-- new (ADR §2b): research scan axis
CREATE INDEX IF NOT EXISTS idx_signals_id_fired ON signals (signal_id, fired_at);

-- ---------------------------------------------------------------- backtest_runs
CREATE TABLE IF NOT EXISTS backtest_runs (
    run_id         TEXT PRIMARY KEY,
    started_at     TEXT NOT NULL,
    finished_at    TEXT,
    signal_id      TEXT,
    signal_version TEXT,
    metadata       TEXT,
    universe       TEXT,
    period_start   TEXT,
    period_end     TEXT
);

-- ---------------------------------------------------------------- paper_trades
CREATE TABLE IF NOT EXISTS paper_trades (
    trade_id       TEXT PRIMARY KEY,
    signal_id      TEXT NOT NULL,
    signal_version TEXT NOT NULL,
    fingerprint    TEXT NOT NULL,
    sizing_scheme  TEXT NOT NULL CHECK (sizing_scheme IN ('flat','log','tier','linear')),
    notional_gbp   DOUBLE PRECISION NOT NULL,
    entry_date     TEXT,
    entry_close    DOUBLE PRECISION,
    shares         DOUBLE PRECISION,
    exit_date      TEXT,
    exit_close     DOUBLE PRECISION,
    status         TEXT NOT NULL CHECK (status IN ('planned','open','closed','skipped')),
    opened_at      TEXT NOT NULL,
    updated_at     TEXT NOT NULL,
    notes          TEXT,
    FOREIGN KEY (fingerprint) REFERENCES transactions (fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_paper_signal ON paper_trades (signal_id, signal_version);
CREATE INDEX IF NOT EXISTS idx_paper_status ON paper_trades (status);

-- ------------------------------------------------------------------------ meta
CREATE TABLE IF NOT EXISTS meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
INSERT INTO meta (key, value) VALUES ('schema_version', '16')
    ON CONFLICT (key) DO NOTHING;

-- ------------------------------------------------------------- reporting_dates
-- Final state after migrations 007/008 (create) + 009 (widen CHECK, add
-- confidence) + 012 (add source_url).
CREATE TABLE IF NOT EXISTS reporting_dates (
    ticker      TEXT NOT NULL,
    report_date TEXT NOT NULL,
    report_type TEXT NOT NULL DEFAULT 'EARNINGS'
                CHECK (report_type IN ('INTERIM','FINAL','TRADING_UPDATE','EARNINGS',
                                       'PRELIM','QUARTERLY','TRADING_STMT')),
    source      TEXT NOT NULL DEFAULT 'yahoo',
    fetched_at  TEXT NOT NULL,
    confidence  TEXT NOT NULL DEFAULT 'confirmed' CHECK (confidence IN ('confirmed','est')),
    source_url  TEXT,
    PRIMARY KEY (ticker, report_date, report_type)
);
CREATE INDEX IF NOT EXISTS idx_reporting_dates_ticker ON reporting_dates (ticker);
CREATE INDEX IF NOT EXISTS idx_reporting_dates_date   ON reporting_dates (report_date);

-- ------------------------------------------------------------- short_positions
CREATE TABLE IF NOT EXISTS short_positions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_holder TEXT,
    issuer_name     TEXT NOT NULL,
    isin            TEXT NOT NULL,
    ticker          TEXT,
    net_short_pct   DOUBLE PRECISION NOT NULL,
    position_date   TEXT NOT NULL,
    source          TEXT NOT NULL DEFAULT 'ssr_daily',
    fetched_at      TEXT NOT NULL,
    UNIQUE (position_holder, isin, position_date, source)
);
CREATE INDEX IF NOT EXISTS idx_short_positions_ticker_date ON short_positions (ticker, position_date);
CREATE INDEX IF NOT EXISTS idx_short_positions_isin        ON short_positions (isin);

-- ------------------------------------------------------------- isin_ticker_map
CREATE TABLE IF NOT EXISTS isin_ticker_map (
    isin      TEXT PRIMARY KEY,
    ticker    TEXT NOT NULL,
    method    TEXT NOT NULL CHECK (method IN ('name_match','openfigi','manual')),
    mapped_at TEXT NOT NULL
);

-- ---------------------------------------------------------------- director_pay
CREATE TABLE IF NOT EXISTS director_pay (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker            TEXT NOT NULL,
    director_key      TEXT NOT NULL,
    director_name_raw TEXT,
    fy_end            TEXT NOT NULL DEFAULT '',
    ar_published_at   TEXT,
    pay_native        DOUBLE PRECISION,
    currency          TEXT,
    fx_rate           DOUBLE PRECISION,
    fx_date           TEXT,
    pay_gbp           DOUBLE PRECISION,
    pay_type          TEXT NOT NULL CHECK (pay_type IN ('single_figure_total','base_salary',
                                                        'ned_fees','fee_waiver_zero','nominal','none')),
    role_class        TEXT,
    pay_status        TEXT NOT NULL DEFAULT 'ok'
                      CHECK (pay_status IN ('ok','new_appointee_no_disclosure','out_of_scope','extraction_fail')),
    source_rung       TEXT CHECK (source_rung IN ('a','b','c') OR source_rung IS NULL),
    source_url        TEXT,
    confidence        TEXT,
    machine_readable  INTEGER NOT NULL DEFAULT 0,
    fetched_at        TEXT NOT NULL,
    UNIQUE (ticker, director_key, fy_end, pay_type)
);
CREATE INDEX IF NOT EXISTS idx_director_pay_join   ON director_pay (ticker, director_key);
CREATE INDEX IF NOT EXISTS idx_director_pay_status ON director_pay (pay_status);

-- ------------------------------------------------------------ conviction_scores
-- Column names match the CODE (migration 016 + export_dashboard_json.py writer +
-- conviction_outcomes.py reader + conviction_pipeline.py + all tests), which is
-- the source of truth for what actually runs: window_end / rank_in_window /
-- surfaced. The LIVE SQLite table carries superseded legacy names
-- (week_start/rank_in_week/surfaced_top3) and is EMPTY (0 rows) because the
-- writer has been failing silently against it in production (column mismatch
-- swallowed by a try/except). Matching the code here FIXES that latent bug —
-- the conviction panel will populate in the cloud. (Verified 2026-06-22.)
CREATE TABLE IF NOT EXISTS conviction_scores (
    fingerprint        TEXT NOT NULL,
    window_end         TEXT NOT NULL,
    scored_at          TEXT NOT NULL,
    score              DOUBLE PRECISION,
    band               TEXT,
    f1_who             DOUBLE PRECISION,
    f2_buy_size        DOUBLE PRECISION,
    f3_company_size    DOUBLE PRECISION,
    f4_earnings_timing DOUBLE PRECISION,
    f5_past_performance DOUBLE PRECISION,
    f6_sector_mult     DOUBLE PRECISION,
    weights_used       TEXT,
    earnings_dropped   INTEGER NOT NULL DEFAULT 0,
    rank_in_window     INTEGER,
    surfaced           INTEGER NOT NULL DEFAULT 0,
    inputs_missing     TEXT,
    PRIMARY KEY (fingerprint, window_end),
    FOREIGN KEY (fingerprint) REFERENCES transactions (fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_conviction_window   ON conviction_scores (window_end);
CREATE INDEX IF NOT EXISTS idx_conviction_surfaced ON conviction_scores (surfaced);
